### ISSUE TITLE
I did not start minikube, i got this issue anyone can help me how to solve this one?

### ISSUE THREAD

**Issue by muhammadali-live** [selikapro/microservices-python#11]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/106036016/202737138-50fc5c69-89d8-4c15-a29d-dd4b3ec76e9a.png">

**Comment by donwany** [comment]
What exactly is the issue?

**Comment by selikapro** [comment]
Yeah, I have the same question that @donwany has. Going to close this issue. If you have an issue please provide details :)
