### ISSUE TITLE
Can't connect to MySQL server on 'host.minikube.internal' (115)

### ISSUE THREAD

**Issue by gitgithan** [selikapro/microservices-python#12]
```
MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")                                              │     43h           │
│ 172.17.0.1 - - [20/Nov/2022 10:19:23] "POST /login HTTP/1.1" 500 -
```
Anyone has idea how to solve this?

Has this got something to do with /etc/hosts settings?

I could not even open mp3converter.com or rabbitmq-manager.com following the video. 
Had to add `192.168.64.2 rabbitmq-manager.com` before i could do that, `127.0.0.1 rabbitmq-manager.com` didn't work (can anyone explain?)
Not sure where 192.168.64.2 comes from or why i must use that in /etc/hosts

My `minikube ssh 'cat /etc/hosts'` shows
```
127.0.0.1       localhost
127.0.1.1       minikube
192.168.64.1    host.minikube.internal
192.168.64.2    control-plane.minikube.internal
```
if this is helpful (not sure what to make of this output)

**Comment by gitgithan** [comment]
Based on https://minikube.sigs.k8s.io/docs/handbook/host-access/#prerequisites it says `The service running on your host must either be bound to all IP’s (0.0.0.0) and interfaces`.
So i changed mysql bind-address from 127.0.0.1 to 0.0.0.0 by editing the file `/usr/local/Cellar/mysql56/5.6.32/homebrew.mxcl.mysql.plist` from answer at https://dba.stackexchange.com/questions/55958/cant-remote-access-mysql-server-running-on-mac-os-x.

After that i changed init.sql user from localhost to %, means `a user that can connect from any host` (https://linuxize.com/post/how-to-create-mysql-user-accounts-and-grant-privileges/)
```
CREATE USER 'auth_user' @'%' IDENTIFIED BY 'Auth123';
CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON auth.* TO 'auth_user' @'%';
```
and 5 hours later i finally got my jwt from /login. 

You could also run sql commands locally to test if your user and ip combinations work instead of testing it by curling and waiting for your container to fail accessing your local mysql, using patterns like
`mysql -h localhost -u auth_user -p` (next prompt will ask for password, then give some error message).
Try changing localhost to other ips to ensure it connects properly from all hosts to check that your bind-address=0.0.0.0 is working. 

`minikube ip` and `minikube ssh 'cat /etc/hosts'` are helpful debugging commands to find what ips are auto-assigned. The ip from `minikube ip` should be the same as the ADDRESS column from `kubectl get ingress`

**Comment by donwany** [comment]
You can close it if its working

**Comment by dkaberna** [comment]
Hi @gitgithan, not sure if you'll see this message, but I have a question for you:

I'm able to obtain a JWT when calling the auth service from within another pod.  But when I try to call the full curl command `curl -X  POST http://mp3converter.com/login....`, I still get `curl: (7) Failed to connect to mp3converter.com port 80 after 0 ms: Connection refused.`

I checked that the IP address when calling `minikube ip` is the same as when calling `kubectl get ingress`.  Any other ideas/suggestions to get this to work?
