### ISSUE TITLE
 The command '/bin/sh -c pip install --no-cache-dir --requirement /app/requirements.txt' returned a non-zero code: 1

### ISSUE THREAD

**Issue by ekagravarma** [selikapro/microservices-python#15]
hi, I was going through the tutorial. I created a dockerFile and while building the image of dockerfile. It was unable to install requirement. I removed the particular software name (eg. apturl==0.5.2) from Dockerfile so that the requirement file gets installed but the image was again not built showing same error ( non-zero code: 1) with different software version.
I have atttached my dockerfile and requirement.txt for your [convinience])
-----------------------------------------------------------------------------------------------------------------------------------------------
Step 3/8 : WORKDIR /app
 ---> Using cache
 ---> 9b03bbc62069
Step 4/8 : COPY ./requirements.txt /app
 ---> Using cache
 ---> 09b7caf2af3f
Step 5/8 : RUN pip install --no-cache-dir --requirement /app/requirements.txt
[requirements.txt](https://github.com/selikapro/microservices-python/files/10088222/requirements.txt)

 ---> Running in 4cf4d2ed059b
**ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from versions: none)
ERROR: No matching distribution found for apturl==0.5.2**
**The command '/bin/sh -c pip install --no-cache-dir --requirement /app/requirements.txt' returned a non-zero code: 1**
![doc](https://user-images.githubusercontent.com/40314122/203890960-1c9912ca-0418-4518-bbe0-80f6123459f6.png)
_____________________________________________________________________________________________

**Comment by selikapro** [comment]
I'm not entirely clear on what the issue is here. Did you change anything in the Dockerfile? are you using a virtual env? Are you adding additional dependencies that aren't in the tutorial? Please provide more details so that I can try to help.

**Comment by donwany** [comment]
But it actually wrong package name, ensure pip search([service disabled](https://github.com/pypa/pip/issues/5216#issuecomment-744605466) at the time of writing), or google, or search on [pypi site](https://pypi.org/) to get the accurate package name: apturl==0.5.2

**Comment by selikapro** [comment]
closing this since no response from @ekagravarma
