### ISSUE TITLE
Mysql cannot be connected using minikube's host.minikube.internal 

### ISSUE THREAD

**Issue by kshitizJ** [selikapro/microservices-python#16]
## Error Image: 
![error](https://user-images.githubusercontent.com/53303745/204094846-9d9572ab-1e8d-452b-8e0d-b17b9c03dd39.png)

## My server file image: 
![pythonfile](https://user-images.githubusercontent.com/53303745/204094917-e1814623-6dc9-4d07-9029-9de9bb569a8a.png)

## My auth-deployment file image:
![auth-deployment-file](https://user-images.githubusercontent.com/53303745/204095016-1b2818fc-07f0-4608-96f9-ab51c3b59dee.png)

## My auth-service file image:
![auth-service](https://user-images.githubusercontent.com/53303745/204095145-bd059d09-f0fa-4934-a487-1949cddb3cec.png)

## My auth-configmap file image:
![auth-configmap](https://user-images.githubusercontent.com/53303745/204095186-bec12115-b22e-46dd-9749-6c1e0dee31b0.png)

## My Docker file for auth:
![auth-docker-file](https://user-images.githubusercontent.com/53303745/204095251-65443b9c-d239-44be-95ca-35fa1b52fc78.png)

## My all pods are running successfully:
![pods running](https://user-images.githubusercontent.com/53303745/204095428-abf64fb0-2f14-4cae-b722-1ad81eeaa677.png)

I don't know what is the error. When id do `systemctl status mysql` it shows that my mysql is running successfully in my local device. 
My operating system is Ubuntu 22.04 LTS.

Please help me to resolve the issue.

**Comment by selikapro** [comment]
My guess is that the mysql credentials aren't configured correctly.

**Comment by kshitizJ** [comment]
## Thank you for replying. 

My mysql credentials are correct. I am able to login using mysql credentials. 
![mysql](https://user-images.githubusercontent.com/53303745/204143219-db215465-f51c-4e70-9cb4-eba5707fc117.png)

**Comment by selikapro** [comment]
I'm talking about the env vars that are being used by the application. can you check or show me the output of `env | grep MYSQL` ?

**Comment by selikapro** [comment]
Ok, so you are sure user `root` and password `Kshitiz@123` are the correct credentials?

**Comment by selikapro** [comment]
Can you show your init.sql

**Comment by kshitizJ** [comment]
## My Env vars used by the application in the container that is connecting to mysql:
![env vars](https://user-images.githubusercontent.com/53303745/204144744-ae54a70b-04e0-42d2-ac98-b078835ef045.png)

> Ok, so you are sure user `root` and password `Kshitiz@123` are the correct credentials?

Yes

## My init.sql file:
![sql file](https://user-images.githubusercontent.com/53303745/204144826-a6e4fe05-d728-4c76-b328-53d6454bf7d8.png)

**Comment by selikapro** [comment]
seems you removed the line `CREATE USER 'auth_user'@'localhost' IDENTIFIED BY 'Auth123';`

You shouldn't remove this you should just replace the values with your creds. 
Actually can you drop the db and then create it again using the `init.sql` from this repo.. you can change the insert line but leave the password and user.. then use those creds in your secrets file and see if it will connect?

**Comment by kshitizJ** [comment]
Sure I will give this a try.

I have a doubt. This new user which we are creating, is being created in our local mysql right?
My local mysql already have a user name - 'root' and password - 'Kshitiz@123' then does it make any difference if we use the existing user i.e 'root' than creating a new user?

**Comment by selikapro** [comment]
I have no way of knowing how your user is configured and what dbs it has access too. I do know that in that init.sql I explicitly give access to the user being created in the script. So if we can't connect even when using that user, we know that the problem is something else. Basically, the fastest way to figure out the problem is through process of elimination.

**Comment by selikapro** [comment]
You also removed the line `GRANT ALL PRIVILEGES ON auth.* TO 'auth_user'@'localhost';` 

These are important

**Comment by kshitizJ** [comment]
> I have no way of knowing how your user is configured and what dbs it has access to. I do know that in that init.sql I explicitly give access to the user being created in the script. So if we can't connect even when using that user, we know that the problem is something else. Basically, the fastest way to figure out the problem is through process of elimination.

Ok, Thank you. I will create a new user and give you an update.

**Comment by kshitizJ** [comment]
Update:

I am getting an error

Init.sql file:
![sql file](https://user-images.githubusercontent.com/53303745/204145968-da4d5098-4a00-4bfc-8bbd-566b0c2a1827.png)


So I added '@' in the password and the user got created.

Still i get the same error: 
![error 2](https://user-images.githubusercontent.com/53303745/204146175-bba4c598-806e-4b43-9d98-3f493a108818.png)

**Comment by kshitizJ** [comment]
## I use this command to run the application:
![command](https://user-images.githubusercontent.com/53303745/204146261-804ee982-620a-4d67-9640-5a00e38674ab.png)

**Comment by selikapro** [comment]
can you `docker exec` into the container and try to manually connect to mysql from within the containers shell?

**Comment by kshitizJ** [comment]
Will you please assist me on this using google meet as I am new to docker and kubernetes.
 
I can share you the meeting link.

**Comment by selikapro** [comment]
for example `sudo docker exec –it container-name /bin/bash`

**Comment by selikapro** [comment]
that command will get you into the container. Then once in the container try to connect using your usual `mysql` command that you use on your local but this time use the host `host.minikube.internal`

**Comment by kshitizJ** [comment]
Do I need to do this `eval $(minikube docker-env)` before getting into the container?

**Comment by selikapro** [comment]
huh why?

**Comment by selikapro** [comment]
Nope just do what I mentioned above. Also I can't get on a call. It's late for me and I have work tomorrow

**Comment by selikapro** [comment]
also, you will need to install a mysql client in the container

**Comment by selikapro** [comment]
I will check on this tomorrow. Let me know the results.

**Comment by kshitizJ** [comment]
Ok I will do as you said and I will update you.

How to install mysql client inside the container?

**Comment by selikapro** [comment]
I think its `apt-get install mysql-client`. This is the underlying os of the container. https://github.com/docker-library/python/blob/7ee840478eed1fd8d36dbe9ab7bd4706085468e5/3.12-rc/slim-bullseye/Dockerfile

You can see how they are installing things in the script

**Comment by kshitizJ** [comment]
Ok got it. I will update you by tomorrow. Thank you so much for the help.

**Comment by kshitizJ** [comment]
> can you `docker exec` into the container and try to manually connect to mysql from within the container's shell?

## From inside the container I got this error:
![inside container](https://user-images.githubusercontent.com/53303745/204150289-28a30bcb-30ea-4378-b209-787e4f217735.png)

**Comment by selikapro** [comment]
Are you sure you have mysql server installed on your local? What os are you using?

**Comment by kshitizJ** [comment]
Yes, I am sure.

OS: Ubuntu 22 LTS

Mysql version:
![mysql-version](https://user-images.githubusercontent.com/53303745/204152386-52a20473-8983-4474-a0be-f1f38e49316f.png)

**Comment by selikapro** [comment]
run this and show me the output please `sudo apt-get install mysql-server`

**Comment by kshitizJ** [comment]
on my local machine?

**Comment by selikapro** [comment]
yes

**Comment by kshitizJ** [comment]
## This is the output:
![Screenshot from 2022-11-27 23-47-33](https://user-images.githubusercontent.com/53303745/204152644-553e366b-7f3f-46e0-b907-611cf5a3d47d.png)

**Comment by kshitizJ** [comment]
Hello sir, will you please suggest me next steps so that I can complete this tutorial. Your teaching is very good. I got to know each and every concepts clearly. I just got stuck because of mysql.

**Comment by donwany** [comment]
did you change the port from "3306" to '3306' in the yaml file?

**Comment by donwany** [comment]
If its still not working just connect to a remote mysql database either on aws or azure. That should work fine

**Comment by donwany** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: root
  MYSQL_DB: auth
  **MYSQL_PORT: '3306'**

kubectl port-forward auth-67f87b9dc6-s7jbg 5000:5000 &

curl -X POST 'http://127.0.0.1:5000/login' -u "theodondre@gmail.com:admin123"
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRoZW9kb25kcmVAZ21haWwuY29tIiwiZXhwIjoxNjY5ODUxOTY2LCJpYXQiOjE2Njk3NjU1NjYsImFkbWluIjp0cnVlfQ.pOSQEACZrnni4NVP9WDr6pO1o6iK0ZWRPPYQWPdsQiI%

**Comment by donwany** [comment]
![Screenshot 2022-11-29 at 5 52 11 PM](https://user-images.githubusercontent.com/10055091/204673962-b12e7224-63ca-404a-a110-466ce5b82ccc.png)

![Screenshot 2022-11-29 at 5 52 20 PM](https://user-images.githubusercontent.com/10055091/204673970-fb8c1158-5fe8-425b-b283-8a6e2590ed5a.png)

**Comment by donwany** [comment]
Not sure why you using python:3.10 for your Dockerfile

**Comment by kshitizJ** [comment]
> did you change the port from "3306" to '3306' in the yaml file?

No luck on this.



> apiVersion: v1 kind: ConfigMap metadata: name: auth-configmap data: MYSQL_HOST: host.minikube.internal MYSQL_USER: root MYSQL_DB: auth **MYSQL_PORT: '3306'**
> 
> kubectl port-forward auth-67f87b9dc6-s7jbg 5000:5000 &
> 
> curl -X POST 'http://127.0.0.1:5000/login' -u "[trump@gmail.com](mailto:trump@gmail.com):admin123"
> 
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRoZW9kb25kcmVAZ21haWwuY29tIiwiZXhwIjoxNjY5ODUxOTY2LCJpYXQiOjE2Njk3NjU1NjYsImFkbWluIjp0cnVlfQ.pOSQEACZrnni4NVP9WDr6pO1o6iK0ZWRPPYQWPdsQiI%


No luck on this as well.


## I got this while hitting the URL through postman:
![postman error](https://user-images.githubusercontent.com/53303745/204887505-8de88d21-a6ea-429e-ae5f-92bb90680d41.png)


Error: 
> MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")

**Comment by kshitizJ** [comment]
## Also when I do minikube tunnel, I get stuck on this:
![Screenshot from 2022-12-01 00-51-32](https://user-images.githubusercontent.com/53303745/204889349-461ed949-07bd-4ffc-8b89-5bc3e9a41d9a.png)

**Comment by selikapro** [comment]
Let's focus on one issue at a time. If you are having issues with minikube tunnel, it's better to create another issue. 

> I think my pods inside the minikube node doesnot have the access of host.minikube.internal

For this, please run the following commands and show me the output:

`minikube ssh`

`nc -vz host.minikube.internal 3306`

**Comment by kshitizJ** [comment]
> Let's focus on one issue at a time. If you are having issues with minikube tunnel, it's better to create another issue.
> 
> > I think my pods inside the minikube node doesnot have the access of host.minikube.internal
> 
> For this, please run the following commands and show me the output:
> 
> `minikube ssh`
> 
> `nc -vz host.minikube.internal 3306`


## output:
![Screenshot from 2022-12-01 21-29-38](https://user-images.githubusercontent.com/53303745/205100395-cc1a506b-5991-4c5d-9fe7-29a284cdfd37.png)

**Comment by selikapro** [comment]
can you show me the output of `ping host.minikube.internals` as well... while in minikube ssh

**Comment by selikapro** [comment]
Looking at [this](https://github.com/kubernetes/minikube/issues/8439), it's possible there was a degradation introduced into the minikube code? I'm not sure I didn't read through it entirely, but what minikube version are you using?

**Comment by kshitizJ** [comment]
> Looking at [this](https://github.com/kubernetes/minikube/issues/8439), it's possible there was a degradation introduced into the minikube code? I'm not sure I didn't read through it entirely, but what minikube version are you using?
> 
> `minikube version`
> 
> Might be worth it to downgrade to the version I used in the tutorial to see if that fixes the issue. In the tutorial I use `v1.25.0` Let me know how it goes


I read some the documentation where it says that if you are using `minikube version greater than 1.10` than you can use `host.minikube.internal` to access the service on your local machine.

**Comment by kshitizJ** [comment]
Ok, I will downgrade and let you know.

Thank you!

**Comment by kshitizJ** [comment]
> Yeah I know that but look at the thread I linked. People with minikube v1.28.x seem to be experiencing the issue you are experiencing. So I'm guessing a bug was introduced at some point between v1.25 and v1.28.. So that's why I said you should try downgrading minikube to the version I used in the tutorial which is v1.25.0

I downgraded the minikube version and the problem still exists.

It says that `MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")`

**Comment by selikapro** [comment]
Ok, so at this point I can't tell if this is an issue with your mysql or what so we are just going to have to do this a different way. Please do the following:

1. Create a directory structure in the`src` dir that looks like this:
![Screen Shot 2022-12-02 at 16 39 55](https://user-images.githubusercontent.com/78267301/205241082-8ac059e7-3951-46dc-9fa3-04142d3c6ffd.png)

2. In the `pod.yaml` file insert this:
```
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql        
    ports:
      - containerPort: 3306
    volumeMounts:
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE USER 'auth_user'@'localhost' IDENTIFIED BY 'Aauth123';
    CREATE DATABASE auth;
    GRANT ALL PRIVILEGES ON auth.* TO 'auth_user'@'localhost';
    USE auth;
    CREATE TABLE user (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL);
    INSERT INTO user (email, password) VALUES ('georgio@email.com', 'Admin123');
```

3. In `auth/manifests/configmap.yaml` replace the contents with this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: mysql
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
```

4. `kubectl delete` EVERYTHING...
5. `kubectl apply` EVERYTHING

**Comment by kshitizJ** [comment]
Ok, I will try this and let you know.

Thank you!

**Comment by kshitizJ** [comment]
## I did what you said and I am getting this error:
![Screenshot from 2022-12-02 20-06-10](https://user-images.githubusercontent.com/53303745/205317084-275435bf-3f9e-4a79-b6f6-85b3c8120912.png)

**Comment by selikapro** [comment]
Come on bro. At least attempt to fix it on your own. You aren't going to learn anything if you ask for the fix before even trying to figure out what the issue is. This is a pretty straightforward error. Don't take it the wrong way. I just want you to actually learn something 😉

**Comment by kshitizJ** [comment]
I did some research but was unsuccessful.

What I did is, I updated the mysql pod and wrote `MYSQL_ALLOW_EMPTY_PASSWORD` to `yes`:
![Screenshot from 2022-12-02 23-42-27](https://user-images.githubusercontent.com/53303745/205359075-e09080c0-7dcc-4301-9b16-ec4654f46aea.png)

Then I deleted the mysql yaml file by `kubectl delete -f ./` and again ran `kubectl delete -f ./`

Then I started mysql at port 3306 (I don't know if it was necessary or not):
![Screenshot from 2022-12-02 23-42-43](https://user-images.githubusercontent.com/53303745/205359373-cdfd441b-4de9-415f-8991-9d0be9b882f0.png)

Then I deleted all the manifest yaml file in auth using command `kubectl delete -f ./` and made changes to config.yaml file as you suggested: 
![Screenshot from 2022-12-02 23-43-38](https://user-images.githubusercontent.com/53303745/205359594-1e85c44d-d9eb-4785-827d-b6354bf2062b.png)

Then I forwarded the port of auth pod:
![Screenshot from 2022-12-02 23-43-53](https://user-images.githubusercontent.com/53303745/205359778-169bd118-f099-4d74-bcdd-5ffb690ff3c6.png)

Then I made request from the command line but was unsuccessful again:
![Screenshot from 2022-12-02 23-50-49](https://user-images.githubusercontent.com/53303745/205359959-eb707fed-7362-4928-9e71-05fd487d57e4.png)

By checking the logs I saw that I have same issue i.e. `MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")`

**Comment by selikapro** [comment]
Can you use the tool I suggested in the video `k9s`. and check if the pod is running? You should see a pod with the `Name` of `mysql`. If not, something went wrong with `kubectl apply`. So Run it again on the mysql dir and show me the output

**Comment by kshitizJ** [comment]
I use kube lens application to check if the pod is running or not.

Here is the image of mysql that is running:
![Screenshot from 2022-12-03 14-16-08](https://user-images.githubusercontent.com/53303745/205432571-e5cd7e97-1c0d-4871-ac86-05e85bf25162.png)

**Comment by selikapro** [comment]
> Then I started mysql at port 3306 (I don't know if it was necessary or not):

Wait, I just noticed. why are you port-forwarding mysql? Please read the doc about what port-forward does. You are trying to connect to the mysql pod that is inside of the cluster with another pod that is inside of the cluster... So why port-forward?

**Comment by kshitizJ** [comment]
It is still not working without port-forwarding.

I am getting the same error.

**Comment by selikapro** [comment]
So you can see that the mysql pod is there. And that the name is in fact `mysql`. And the error is that the mysql host with the name `mysql` doesn't exist. So seems to me you need to research how pods can communicate with other pods internally (within a kubernetes cluster). 

Do some troubleshooting e.g. try to connect to the mysql db from your local by using port forwarding.. You need to try things. 

That should help you figure out your issue. I think at this point, I've provided a lot of guidance but I think I'd be doing you a disservice if I keep walking you through every step so I'm going to let you figure this one out on your own. When you solve the problem, please let me know as I'll be happy to hear about it. But other than that, I'm going to let you troubleshoot on your own and learn.

**Comment by kshitizJ** [comment]
Ok, I will let you know once I troubleshoot the problem.

Thanks once again for the guidance.

**Comment by selikapro** [comment]
Hey bro, any update? What have you been trying so far?

**Comment by kshitizJ** [comment]
> apiVersion: v1 kind: ConfigMap metadata: name: auth-configmap data: MYSQL_HOST: host.minikube.internal MYSQL_USER: root MYSQL_DB: auth **MYSQL_PORT: '3306'**
> 
> kubectl port-forward auth-67f87b9dc6-s7jbg 5000:5000 &
> 
> curl -X POST 'http://127.0.0.1:5000/login' -u "[trump@gmail.com](mailto:trump@gmail.com):admin123"
> 
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRoZW9kb25kcmVAZ21haWwuY29tIiwiZXhwIjoxNjY5ODUxOTY2LCJpYXQiOjE2Njk3NjU1NjYsImFkbWluIjp0cnVlfQ.pOSQEACZrnni4NVP9WDr6pO1o6iK0ZWRPPYQWPdsQiI%


Which OS are you using?

**Comment by donwany** [comment]
> 

MAC OS

**Comment by selikapro** [comment]
> Than I tried the mysql host which is running in the container but still no luck.
What do you mean by no luck here? What happened?

**Comment by kshitizJ** [comment]
> MAC OS

ok

**Comment by andreariba** [comment]
I got the same issue on 
`😄  minikube v1.28.0 on Ubuntu 22.04`

**Comment by andreariba** [comment]
the workaround on AppArmor from https://github.com/kubernetes/minikube/issues/7401 did not work for me

**Comment by lewiswon** [comment]
> 

Your error may not same with this one, I have same error with you, I tried #4 method, and now is work.

**Comment by lewiswon** [comment]
> I got the same issue on `😄 minikube v1.28.0 on Ubuntu 22.04`

Your error may not same with this one, I have same error with you, I tried #4 method, and now is work.

**Comment by andreariba** [comment]
already tried not working

> > I got the same issue on `😄 minikube v1.28.0 on Ubuntu 22.04`
> 
> Your error may not same with this one, I have same error with you, I tried #4 method, and now is work.

**Comment by juanfrilla** [comment]
@andreariba did you finally solve it? I have the same error `Mysql connection cursor error on cur = mysql.connection.cursor() TypeError: 'str' object cannot be interpreted as an integer`

**Comment by andreariba** [comment]
the course is basically mac os specific, and there are too many differences in the configuration of minikube and mysql for ubuntu, if you find a solution let me know

> @andreariba or @kshitizJ did you finally solve it? I have the same error `Mysql connection cursor error on cur = mysql.connection.cursor() TypeError: 'str' object cannot be interpreted as an integer` And when I cast the int, now my error is `MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")`

**Comment by selikapro** [comment]
> the course is basically mac os specific, and there are too many differences in the configuration of minikube and mysql for ubuntu, if you find a solution let me know
> 
> > @andreariba or @kshitizJ did you finally solve it? I have the same error `Mysql connection cursor error on cur = mysql.connection.cursor() TypeError: 'str' object cannot be interpreted as an integer` And when I cast the int, now my error is `MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")`

The fact that the entire architecture is run in a vm (minikube is basically just a virtual machine) means that the course is inherently not OS specific. The issue that people are experiencing here is that they can't connect to their localhost from within minikube. I provided the MacOS solution for this in the course and I assumed the solution would be similar for other operating systems but it seems that is not the case. 

For that reason, I provided an alternative solution that allows you to run mysql within the cluster which @knowbits was able to successfully implement and he also provided a very well written detailed explanation of how. A course is meant to offer guidance for others to learn from. In programming, when doing literally anything, you will run into issues that require you to figure out ways to resolve them. This is where you learn the most.

Things in this field are very rarely a,b,c 1,2,3 and DONE without issues. Especially when somebody makes a 5 hour course that attempts to teach people how to build an entire architecture. The more complex something is, the more likely there are to be issues. 

But I still think that everybody here can solve their issues by simply spinning up a mysql pod within the cluster. And even if you can't get it working, I still hope that you were able to learn something.

**Comment by juanfrilla** [comment]
> > Same error. `MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")`
> 
> Been having the same MySQL connection problems, @kshitizJ.
> 
> Finally got it working, the JWT is now returned (!) when calling: `curl -X POST http://mp3converter.com/login -u georgio@email.com:Admin123`
> 
> I suspect that trying to access a MySQL db installed in Windows/WSL/Ubuntu using "host.minikube.internal" might be the culprit. Solution: Run MySQL in Kubernetes as @selikapro suggested.
> 
> 1. Follow the instructions above by @selikapro and run mysql in the cluster, so create the "pod.yaml" as described above.
> 2. NOTE: There is typo in that "pod.yaml", change "Aauth123" to "Auth123"
> 3. Then create a "service.yaml" file to expose the mysql pod as a service, so that it can be called using "mysql" from other pods in the cluster. See below.
> 4. I also had to make one more change in the "init.sql" part of "pod.yaml": replace 'localhost' with '172.17.0.1'
> 
> PS! You might need to add a label to "pod.yaml", to be able to refer to it from "service.yaml":
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: mysql
>   labels:
>     app: mysql
> # Only the last two lines were added.
> # Rest of file not included..
> ```
> 
> The "service.yaml":
> 
> ```yaml
> apiVersion: v1
> kind: Service
> metadata:
>   name: mysql
> spec:
>   selector:
>     app: mysql
>   type: ClusterIP
>   ports:
>     - port: 3306
>       targetPort: 3306
>       protocol: TCP
> ```
> 
> Useful: Connect "mysql" tool to the Kubernetes pod
> 
> * Exposing it to port 7777, to avoid using same port as the "mysql" service running in WLS/Ubuntu.
> * `$ kubectl port-forward mysql 7777:3306`
> * `$ mysql --user=auth_user --password=Auth123 --port=7777`

Thanks! I followed all the steps and It worked ;-)

**Comment by juanfrilla** [comment]
@knowbits thanks! Followed all the steps and it worked 😉

**Comment by juanfrilla** [comment]
@knowbits I am not able to complete it still, I'm struggling with MongoDB stuff 😅

**Comment by juanfrilla** [comment]
@knowbits  I am not able to complete it yet, I'm struggling with the MongoDB stuff 😅 
I'm wondering if we need to create some others yml files for mongo configuration because I don't know if it would give error of "host.minikube.internal" unrecognized host or something like that

**Comment by juanfrilla** [comment]
@knowbits finally got it, with mongodb yml files. Let me know if you want to know the steps and the files I used

**Comment by juanfrilla** [comment]
@knowbits finally could implement my MongoDB pod in kubernetes creating a persistent volume, persistent volume claim, a service and a deployment of mongo following this tutorial https://levelup.gitconnected.com/deploy-your-first-flask-mongodb-app-on-kubernetes-8f5a33fa43b4
And changed "host.minikube.internal" by "mongo" in the python code
Now the upload endpoint is working and there I stayed, tomorrow I will continue

**Comment by kshitizJ** [comment]
# This is for Linux Ubuntu 22.04 LTS

Hey, I got the JWT by making mysql cluster in kubernetes.

I followed @knowbits but failed to load mysql cluster because it was giving me errors.

Here is my mysql files for making a cluster:

## deployment.yaml - for mysql
```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/minesql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
```

## volume.yaml - for mysql
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
```

I will also share my updated configmap.yaml and secret.yaml files for `auth` service

## configmap.yaml - for auth
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: mysql
  MYSQL_USER: root
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
```

## secret.yaml - for auth
```
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: password
  JWT_SECRET: sarcasm
type: Opaque
```

Now I can follow along with the tutorial. Thank you for your help. If I face any issue ahead then I will open new issue thread.

**Comment by selikapro** [comment]
You guys are great! Congrats 😄
