### ISSUE TITLE
Can't find the "python3.10-slim-bullseye" on Docker Hub

### ISSUE THREAD

**Issue by sshu2017** [selikapro/microservices-python#17]
![Screenshot from 2022-11-26 22-29-40](https://user-images.githubusercontent.com/66704517/204122448-a85e97eb-8d87-44c7-8b60-505a47e4029a.png)
Am I missing something here?

**Comment by selikapro** [comment]
Just type in python then click the slim-bullseye image.

Python images: https://hub.docker.com/_/python

![Screen Shot 2022-11-27 at 23 34 24](https://user-images.githubusercontent.com/78267301/204140841-15488843-40f3-4b9b-845a-9fd9b580487c.png)
