### ISSUE TITLE
Upload route got exxception at util.upload due to pymongo.errors.ServerSelectionTimeoutError: host.minikube.internal:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by SpringWangLA** [selikapro/microservices-python#21]
**Error image:**
![image](https://user-images.githubusercontent.com/88442968/205956828-47e0ac77-ae7e-4783-a90a-cb47004c634b.png)

**My server.py file:** I think there must be something wrong with my MONGO_URI, but somehow, cannot see where this setting is came from, even in your tutorial.
![image](https://user-images.githubusercontent.com/88442968/205957059-b67a67dc-b612-4f71-8860-59123e1ae18c.png)

**My util.py at /storage:** Please note that I change the try-except so my server one can print out the error, dunno why I cannot use the print error to see in the logs command of kubectl
![image](https://user-images.githubusercontent.com/88442968/205957355-a5010e91-cc46-4bdc-9ede-2e89e9216631.png)

**Comment by selikapro** [comment]
Thanks for providing details. What OS are you using? Pretty sure this is related to [this](https://github.com/selikapro/microservices-python/issues/16)

Do you have the same issue with MySQL?

**Comment by juanfrilla** [comment]
@knowbits yes, and in `converter/consumer.py`
 The client will be, `client = MongoClient("mongo", 27017)`

**Comment by selikapro** [comment]
Thanks @knowbits 

Since this issue is already resolved [here](https://github.com/selikapro/microservices-python/issues/16) 

Please refer to the great info provided by others in that thread. Will close this issue.

**Comment by SpringWangLA** [comment]
Well noted and thank you all for your support.

**Comment by simonprudhomme** [comment]
It helps me so much! Thank you! 
I am on MacOs M1
