### ISSUE TITLE
Unable to create tunnel between gateway-ingress and rabbitmq-ingress

### ISSUE THREAD

**Issue by mihir1739** [selikapro/microservices-python#22]
`Status:
        machine: minikube
        pid: 391461
        route: 10.96.0.0/12 -> 192.168.49.2
        minikube: Running
        services: []
    errors: 
                minikube: no errors
                router: no errors
                loadbalancer emulator: no errors`
This is what logs continuously in my stdout. Someone please help!

**Comment by selikapro** [comment]
Guys seriously... there is NOTHING here for somebody to help you 😆 

Closing this, please provide more details.
