### ISSUE TITLE
MongoDB setup

### ISSUE THREAD

**Issue by sprider** [selikapro/microservices-python#26]
@selikapro 

First of all, thank you so much for this course. 

Any plans to add MongoDB setup instruction for Microservice Architecture and System Design with Python & Kubernetes – Full Course? 

Can we use the approach explained in this(https://www.youtube.com/watch?v=MQZ-WXZbU4w) video? If so, what will be the URI value? 

mongo_video = PyMongo(server, uri="mongodb://host.minikube.internal:27017/videos")
mongo_mp3 = PyMongo(server, uri="mongodb://host.minikube.internal:27017/mp3s")

**Comment by sprider** [comment]
@selikapro, I have solved the MongoDB issues with the help of official MongoDB documentation. Could we please close this issue? 

Also, Here are the most used commands in this tutorial. Please take a look and feel free to include it in your repo.

# important commands used in this course

## minikube

start minikube cluster

`minikube start`

stop minikube cluster

`minikube stop`

expose a service to the internet. run in a separate terminal window to keep the tunnel running. it will ask for sudo password.

`minikube tunnel`

## kubectl

create or update resources using the data in one or more files in the given path

`kubectl apply -f ./`

delete resources using the data in one or more files in the given path

`kubectl delete -f ./`

stream pod logs (stdout)

`kubectl logs -f [pod_name]`

scale a deployment by deployment name and replicas count

`kubectl scale deployment/[deployment_name] --replicas=[count]`

## curl

get access token from auth

`curl -X POST http://mp3converter.com/login -u [username]:[password]`

upload mkv file to mongodb via gateway

`curl -X POST 'http://mp3converter.com/upload' -H 'Authorization: Bearer [access_token]' -F 'file=@[file/path]/[file_name].mkv'`

download mp3 file using file id from mongodb via gateway

`curl -X GET 'http://mp3converter.com/download?fid=[file_id]' -H 'Authorization: Bearer [access_token]' --output sample.mp3`

## docker

build an image from a Dockerfile

`docker build .`

tag image with tag id into the repository with tag

`docker tag [tag_id]] [repository]/[image]:[tag]`

push an image to a registry

`docker push [repository]/[image]:[tag]`  

execute an interactive sh shell on a running container

`docker exec -it [container_id] /bin/sh`

fetch the logs of a container

`docker logs -f --name [container_name]`

## python3

creating virtual environment

`python3 -m venv [virtual_environment_name]`

activate virtual environment

`source [virtual_environment_name]/bin/activate`

output installed packages in requirements format

`pip3 freeze > requirements.txt`

install packages with pip3 from requirements file

`pip3 install -r requirements.txt`

install package with pip3

`pip3 install [package_name]`

**Comment by juanfrilla** [comment]
@sprider please, can you send the link of these instructions? Im not able to get it up and running

**Comment by sprider** [comment]
@juanfrilla I have followed the instructions given [here](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/). 

Please create videos and mp3s databases using 'use' command.

**Comment by simonprudhomme** [comment]
@sprider Can you provide more detail?
I am stuck.
