### ISSUE TITLE
Build with docker compose 

### ISSUE THREAD

**Issue by slalit360** [selikapro/microservices-python#3]
Add guide to the readme file about local run and development.

Add instructions to setup minikube locally and kubernetes

**Comment by donwany** [comment]
You can visit minikube page: https://minikube.sigs.k8s.io/docs/start/

**Comment by selikapro** [comment]
Alternatively, please feel free to create a PR to update the README @slalit360

**Comment by selikapro** [comment]
Since this is a valid request. I will leave this one open for now.

**Comment by selikapro** [comment]
I will close this. If it comes up again we can just create another issue.

**Comment by juanfrilla** [comment]
@selikapro what would be the difference of this project implemented with docker-compose instead of kubernetes?
Thanks

**Comment by selikapro** [comment]
Hmm, I wasn't thinking about docker-compose as a replacement for kubernetes when I said that this was a valid request. I was just thinking that it would be valid to use it for development. I've only ever used docker-compose for local development and I don't think it would be a good solution for deploying a distributed system to a production environment.
