### ISSUE TITLE
Can't send emails ... Gmail less secure no longer available

### ISSUE THREAD

**Issue by blakejoy** [selikapro/microservices-python#5]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/9423898/201486341-2876fed3-92f8-4618-a255-90010333dd75.png">

You need to enable 2FA on your Google account .

It will allow you to generate an app password for "Mail".

You should be able to send emails now.

**Comment by donwany** [comment]
This works, it can be closed

**Comment by selikapro** [comment]
@blakejoy Thanks! closing this
